services:
  backend:
    build: ./backend
    container_name: finance-backend
    env_file:
      - ./backend/.env
    restart: unless-stopped
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: finance-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
